# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNZhuKu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNZhuKu
    pod 'IQKeyboardManager'

  #target 'RNZhuKu-tvOSTests' do
   #inherit! :search_paths
    # Pods for testing
  #end

  #target 'RNZhuKuTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end

target 'RNZhuKu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNZhuKu-tvOS

  target 'RNZhuKu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
